name: Build HTML File

on:
  push:
    branches: [ main ]

jobs:
  upload-validation-dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dhall-lang/setup-dhall@v4
        with:
          version: '1.41.0'

      - name: build html file
        run: |
          sudo apt install -y dhall
          mkdir html
          dhall text <generate.dhall >html/openmls-validation-dashboard.html

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: openmls-validation-dashboard.html
          path: html/openmls-validation-dashboard.html
