name: Build HTML File

on:
  push:
    branches: [ main ]

jobs:
  upload-validation-dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build html file
        run: |
          sudo apt install -y dhall
          mkdir html
          dhall text <generate.dhall >html/index.html
          cp axist.css html/

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: validation-overview
          path: html
